### ISSUE TITLE
Cannot activate the plugin

### ISSUE THREAD

**Issue by Daniel3356** [timersys/geotargeting-pro#15]
Hi, 
I successfully installed the plugin but when I try to activate the plugin I have this error:

Warning: require(/var/www/html/wp-content/plugins/geotargeting-pro-master/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/wp-content/plugins/geotargeting-pro-master/includes/class-geotarget.php on line 222

Fatal error: require(): Failed opening required '/var/www/html/wp-content/plugins/geotargeting-pro-master/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/html/wp-content/plugins/geotargeting-pro-master/includes/class-geotarget.php on line 222

That should I do to be able to activate the plugin and use it. 
Thank you

**Comment by gonzalesc** [comment]
Hi.
This plugin is out of date.
Now the official plugin is here: [https://github.com/timersys/geotargetingwp-plugin](https://github.com/timersys/geotargetingwp-plugin) but you need a license key from [https://geotargetingwp.com/](https://geotargetingwp.com/)


Besides, you must execute `composer update` when starting the project
Regards
